name: SIR
version: 1.0.0
author: Lawrence Murray
email: lawrence.murray@csiro.au
website-url: http://www.github.com/lawmurray/SIR
download-url: http://www.github.com/lawmurray/SIR/archive/master.tar.gz
github-url: http://www.github.com/lawmurray/SIR
description: Susceptible/infectious/recovered epidemiological compartmental model for Russian influenza data set.
